version: 2
jobs:
  # build:
  #   docker:
  #     - image: circleci/node:12.13.0
  #     # - image: postgres:9.4.1
  #     - image: circleci/postgres:9.4.12-alpine
  #   working_directory: ~/project
  #   steps:
  #     - checkout
  ci_api_container:
    docker:
      - image: circleci/node:12.13.0
      - image: circleci/postgres:9.4.12-alpine
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: Update dependencies
          command: |
            cd ./packages/api-server
            npm run install --only=prod
      - run:
          name: Run all migrations
          command: |
            cd ./packages/api-server
            npm run typeorm migration:run
      - run:
          name: Run all tests
          command: |
            cd ./packages/api-server
            npm run test:all
  # test:
  #   docker:
  #     - image: circleci/node:12.13.0
  #     - image: circleci/postgres:9.4.12-alpine
  #   working_directory: ~/project
  #   steps:
  #     - run:
  #         name: Run all tests
  #         command: |
  #           cd ./packages/api-server
  #           npm run test:all

workflows:
  version: 2
  build_and_test:
    jobs:
      # - build
      - ci_api_container
      # - test
