version: 2
jobs:
  build:
    docker:
      # using custom image, see .circleci/images/primary/Dockerfile
      - image: circleci/node:12.13.0
      # - image: postgres:9.4.1
      # - image: circleci/ruby:2.4-node-jessie
      - image: circleci/postgres:9.4.12-alpine
    working_directory: ~/circleci-demo-workflows
    steps:
      - checkout
  prepare_api_container:
    docker:
      - image: circleci/node:12.13.0
      - image: circleci/postgres:9.4.12-alpine
    working_directory: ~/circleci-demo-workflows/packages/api-server
    steps:
      - run:
          name: Run all migrations
          command: |
            npm run install --only=prod
            npm run typeorm migration:run
  test:
    docker:
      - image: circleci/node:12.13.0
      - image: circleci/postgres:9.4.12-alpine
     working_directory: ~/circleci-demo-workflows/packages/api-server
      - run:
          name: Run all tests
          command: |
            npm run test:all

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - prepare_api_container
      - test
     